[build]
  command = "npm run build && rm -rf dist/server"
  publish = "dist/client"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
